### ISSUE TITLE
Test model locally on an AMD machine to see why it's failing and if it is possible to build an image at all.

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos2re5#14]

**Comment by Larraitz5** [comment]
Hi!

I was wondering if the issue has been resolved. I would like to reproduce it.
Is it possible to build a Docker image using the current Dockerfile?

Thank you!

**Comment by GemmaTuron** [comment]
Hi @Larraitz5 

This model is quite old (using ADMET2.0) so we have stopped working on it. We suggest using ADMET3.0 or ADMET-AI, both newer models to predict ADME properties.

**Comment by Larraitz5** [comment]
Hi @GemmaTuron 

Thank you for your prompt reponse and the information provided.
